# Generated by Django 5.1.6 on 2026-07-28 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_alter_photo_options_photo_price_cents_purchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='download_email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='purchase',
            name='download_email_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
